import { Item, Monster, NPC, Quest, HeroSkill } from '../types';

export const ITEMS: Record<string, Item> = {
  // Consumables
  hp_potion: {
    id: 'hp_potion',
    name: 'Elixir of Vitality',
    type: 'consumable',
    rarity: 'common',
    description: 'Restores 45 Hit Points instantly.',
    price: 15,
    icon: 'FlaskConical',
    effect: { healHp: 45 },
  },
  large_hp_potion: {
    id: 'large_hp_potion',
    name: 'Greater Vitality Brew',
    type: 'consumable',
    rarity: 'uncommon',
    description: 'Restores 120 Hit Points.',
    price: 40,
    icon: 'FlaskRound',
    effect: { healHp: 120 },
  },
  mp_potion: {
    id: 'mp_potion',
    name: 'Arcane Draught',
    type: 'consumable',
    rarity: 'common',
    description: 'Restores 35 Mana Points.',
    price: 18,
    icon: 'Sparkles',
    effect: { healMp: 35 },
  },
  fire_bomb: {
    id: 'fire_bomb',
    name: 'Alchemical Fire Bomb',
    type: 'consumable',
    rarity: 'uncommon',
    description: 'Hurls an explosive sphere dealing 60 fire damage.',
    price: 35,
    icon: 'Flame',
    effect: { damage: 60 },
  },

  // Weapons
  rusty_sword: {
    id: 'rusty_sword',
    name: 'Iron Broadsword',
    type: 'weapon',
    rarity: 'common',
    description: 'A reliable iron blade forged by village smiths.',
    price: 25,
    icon: 'Sword',
    stats: { attack: 8 },
  },
  oak_staff: {
    id: 'oak_staff',
    name: "Archon's Oak Staff",
    type: 'weapon',
    rarity: 'common',
    description: 'Infused with gentle woodland leyline energies.',
    price: 25,
    icon: 'Wand2',
    stats: { magic: 9, attack: 3 },
  },
  silver_dagger: {
    id: 'silver_dagger',
    name: "Shadowstalker's Fang",
    type: 'weapon',
    rarity: 'uncommon',
    description: 'Fast and lightweight with high critical precision.',
    price: 65,
    icon: 'Scissors',
    stats: { attack: 14, crit: 15, speed: 4 },
  },
  sunblade: {
    id: 'sunblade',
    name: 'Dawnbreaker Sunblade',
    type: 'weapon',
    rarity: 'rare',
    description: 'Harnesses radiant solar fury against undead and shadowy fiends.',
    price: 180,
    icon: 'Sun',
    stats: { attack: 28, magic: 12, crit: 10 },
  },
  dragon_slayer: {
    id: 'dragon_slayer',
    name: 'Obsidian Wyrmreaver',
    type: 'weapon',
    rarity: 'legendary',
    description: 'A mythical blade forged in dragonfire to sunder behemoths.',
    price: 500,
    icon: 'Flame',
    stats: { attack: 55, crit: 20, hpMax: 40 },
  },

  // Armor
  leather_tunic: {
    id: 'leather_tunic',
    name: 'Traveler Leather Jerkin',
    type: 'armor',
    rarity: 'common',
    description: 'Flexible tanned leather providing modest defense.',
    price: 30,
    icon: 'Shield',
    stats: { defense: 6, hpMax: 15 },
  },
  iron_plate: {
    id: 'iron_plate',
    name: 'Oakhaven Knight Cuirass',
    type: 'armor',
    rarity: 'uncommon',
    description: 'Heavy tempered iron breastplate.',
    price: 90,
    icon: 'ShieldAlert',
    stats: { defense: 18, hpMax: 35 },
  },
  mystic_robe: {
    id: 'mystic_robe',
    name: 'Astral Weaver Vestment',
    type: 'armor',
    rarity: 'rare',
    description: 'Woven with mana-conducting celestial silk.',
    price: 160,
    icon: 'Sparkle',
    stats: { defense: 12, magic: 22, mpMax: 50 },
  },

  // Shields & Offhands
  wooden_buckler: {
    id: 'wooden_buckler',
    name: 'Reinforced Oak Shield',
    type: 'shield',
    rarity: 'common',
    description: 'Blocks incoming blows with solid oak.',
    price: 20,
    icon: 'Shield',
    stats: { defense: 5, hpMax: 10 },
  },
  paladin_aegis: {
    id: 'paladin_aegis',
    name: 'Aegis of the Sun Ward',
    type: 'shield',
    rarity: 'rare',
    description: 'Gleaming kite shield that deflects dark sorcery.',
    price: 140,
    icon: 'ShieldCheck',
    stats: { defense: 22, hpMax: 30, magic: 8 },
  },

  // Helmets
  iron_helm: {
    id: 'iron_helm',
    name: 'Vanguard Helm',
    type: 'helmet',
    rarity: 'common',
    description: 'Standard protective helm for recruits.',
    price: 25,
    icon: 'Crown',
    stats: { defense: 4, hpMax: 8 },
  },
  crown_of_shadows: {
    id: 'crown_of_shadows',
    name: 'Diadem of Nethergale',
    type: 'helmet',
    rarity: 'epic',
    description: 'A dark crystal coronet pulsating with ancient void arcane.',
    price: 260,
    icon: 'Moon',
    stats: { magic: 26, crit: 12, mpMax: 40 },
  },

  // Boots
  leather_boots: {
    id: 'leather_boots',
    name: 'Scout Striders',
    type: 'boots',
    rarity: 'common',
    description: 'Lightweight boots that enhance foot speed.',
    price: 20,
    icon: 'Footprints',
    stats: { speed: 3, defense: 2 },
  },
  windrunner_greaves: {
    id: 'windrunner_greaves',
    name: 'Zephyrwind Greaves',
    type: 'boots',
    rarity: 'rare',
    description: 'Enchanted with mountain gusts for swift maneuvers.',
    price: 130,
    icon: 'Wind',
    stats: { speed: 8, defense: 8, crit: 6 },
  },

  // Accessories
  ruby_ring: {
    id: 'ruby_ring',
    name: 'Bloodstone Signet',
    type: 'accessory',
    rarity: 'uncommon',
    description: 'A crimson gem that pulses with physical vitality.',
    price: 80,
    icon: 'Gem',
    stats: { attack: 6, hpMax: 25 },
  },
  amulet_of_eternity: {
    id: 'amulet_of_eternity',
    name: 'Chronos Celestial Pendant',
    type: 'accessory',
    rarity: 'legendary',
    description: 'A relic of lost Eldoria that bends time and fortune.',
    price: 600,
    icon: 'Sparkles',
    stats: { attack: 15, magic: 20, defense: 15, speed: 6, crit: 15, hpMax: 50, mpMax: 50 },
  },
};

export const CLASS_SKILLS: Record<string, HeroSkill[]> = {
  Warrior: [
    {
      id: 'slash',
      name: 'Power Strike',
      description: 'A ferocious weapon cleave dealing 140% physical damage.',
      mpCost: 8,
      power: 1.4,
      type: 'attack',
      element: 'physical',
      levelReq: 1,
      icon: 'Sword',
    },
    {
      id: 'shield_bash',
      name: 'Shield Slam',
      description: 'Stuns the foe and grants defensive fortitude.',
      mpCost: 14,
      power: 1.2,
      type: 'attack',
      element: 'physical',
      levelReq: 2,
      icon: 'Shield',
    },
    {
      id: 'blade_tempest',
      name: 'Whirlwind Tempest',
      description: 'Unleashes a sweeping vortex of steel dealing 220% damage.',
      mpCost: 24,
      power: 2.2,
      type: 'attack',
      element: 'physical',
      levelReq: 4,
      icon: 'Wind',
    },
  ],
  Mage: [
    {
      id: 'fireball',
      name: 'Ignite Fireball',
      description: 'Hurls an explosive flame orb dealing heavy fire magic damage.',
      mpCost: 12,
      power: 1.6,
      type: 'magic',
      element: 'fire',
      levelReq: 1,
      icon: 'Flame',
    },
    {
      id: 'frost_nova',
      name: 'Frost Blizzard',
      description: 'Chills the target with piercing subzero ice shards.',
      mpCost: 18,
      power: 1.9,
      type: 'magic',
      element: 'ice',
      levelReq: 2,
      icon: 'CloudSnow',
    },
    {
      id: 'arcane_blast',
      name: 'Eldritch Singularity',
      description: 'Tears reality to discharge catastrophic celestial energy (280% magic).',
      mpCost: 32,
      power: 2.8,
      type: 'magic',
      element: 'holy',
      levelReq: 4,
      icon: 'Sparkles',
    },
  ],
  Rogue: [
    {
      id: 'backstab',
      name: 'Shadow Ambush',
      description: 'Strikes from the shadows with high guaranteed critical potency.',
      mpCost: 10,
      power: 1.5,
      type: 'attack',
      element: 'physical',
      levelReq: 1,
      icon: 'Zap',
    },
    {
      id: 'poison_dart',
      name: 'Venom Flurry',
      description: 'Coats blades in deadly viper venom causing continuous agony.',
      mpCost: 15,
      power: 1.7,
      type: 'attack',
      element: 'physical',
      levelReq: 2,
      icon: 'Skull',
    },
    {
      id: 'death_strike',
      name: 'Assassinate',
      description: 'Executes a lethal sequence targeting vital pressure points.',
      mpCost: 26,
      power: 2.6,
      type: 'attack',
      element: 'physical',
      levelReq: 4,
      icon: 'Crosshair',
    },
  ],
  Paladin: [
    {
      id: 'holy_strike',
      name: 'Radiant Smite',
      description: 'Infuses weapon with sacred light dealing combined physical and holy damage.',
      mpCost: 10,
      power: 1.4,
      type: 'attack',
      element: 'holy',
      levelReq: 1,
      icon: 'Sun',
    },
    {
      id: 'divine_heal',
      name: 'Grace of Light',
      description: 'Channels celestial grace to restore 90 HP.',
      mpCost: 16,
      power: 90,
      type: 'heal',
      element: 'holy',
      levelReq: 2,
      icon: 'HeartHandshake',
    },
    {
      id: 'sanctuary_wrath',
      name: "Heaven's Judgment",
      description: 'Calls down divine pillar of wrath to obliterate evil.',
      mpCost: 28,
      power: 2.4,
      type: 'magic',
      element: 'holy',
      levelReq: 4,
      icon: 'Sparkles',
    },
  ],
};

export const MONSTERS: Record<string, Monster> = {
  forest_wolf: {
    id: 'forest_wolf',
    name: 'Timber Wolf',
    level: 1,
    hp: 45,
    maxHp: 45,
    mp: 10,
    attack: 11,
    defense: 4,
    magic: 2,
    speed: 12,
    xpReward: 25,
    goldReward: 12,
    lootTable: [
      { item: ITEMS.hp_potion, chance: 0.5 },
      { item: ITEMS.leather_boots, chance: 0.15 },
    ],
    skills: [{ name: 'Feral Bite', damage: 14, mpCost: 0 }],
    spriteColor: '#78716c',
    avatarIcon: '🐺',
  },
  goblin_raider: {
    id: 'goblin_raider',
    name: 'Goblin Pillager',
    level: 2,
    hp: 65,
    maxHp: 65,
    mp: 15,
    attack: 16,
    defense: 6,
    magic: 5,
    speed: 14,
    xpReward: 45,
    goldReward: 24,
    lootTable: [
      { item: ITEMS.hp_potion, chance: 0.6 },
      { item: ITEMS.rusty_sword, chance: 0.25 },
      { item: ITEMS.wooden_buckler, chance: 0.2 },
    ],
    skills: [
      { name: 'Rusty Shank', damage: 18, mpCost: 0 },
      { name: 'Pocket Sand', damage: 8, mpCost: 5 },
    ],
    spriteColor: '#16a34a',
    avatarIcon: '👺',
  },
  crypt_skeleton: {
    id: 'crypt_skeleton',
    name: 'Crypt Skeleton Guard',
    level: 3,
    hp: 95,
    maxHp: 95,
    mp: 20,
    attack: 22,
    defense: 12,
    magic: 8,
    speed: 9,
    xpReward: 75,
    goldReward: 40,
    lootTable: [
      { item: ITEMS.large_hp_potion, chance: 0.4 },
      { item: ITEMS.iron_helm, chance: 0.25 },
      { item: ITEMS.ruby_ring, chance: 0.15 },
    ],
    skills: [
      { name: 'Bone Cleave', damage: 24, mpCost: 0 },
      { name: 'Curse of Decay', damage: 16, mpCost: 8 },
    ],
    spriteColor: '#e2e8f0',
    avatarIcon: '💀',
  },
  shadow_sorcerer: {
    id: 'shadow_sorcerer',
    name: 'Malakor the Voidcaller',
    level: 5,
    hp: 240,
    maxHp: 240,
    mp: 90,
    attack: 28,
    defense: 16,
    magic: 38,
    speed: 15,
    xpReward: 250,
    goldReward: 160,
    isBoss: true,
    lootTable: [
      { item: ITEMS.sunblade, chance: 0.4 },
      { item: ITEMS.crown_of_shadows, chance: 0.35 },
      { item: ITEMS.mystic_robe, chance: 0.35 },
    ],
    skills: [
      { name: 'Void Bolt', damage: 32, mpCost: 15, element: 'ice' },
      { name: 'Shadow Eclipse', damage: 45, mpCost: 25, element: 'fire' },
      { name: 'Life Drain', damage: 25, mpCost: 12 },
    ],
    spriteColor: '#7c3aed',
    avatarIcon: '🧙‍♂️',
  },
  molten_drake: {
    id: 'molten_drake',
    name: 'Ignis Prime Dragon',
    level: 7,
    hp: 450,
    maxHp: 450,
    mp: 120,
    attack: 48,
    defense: 28,
    magic: 42,
    speed: 18,
    xpReward: 600,
    goldReward: 350,
    isBoss: true,
    lootTable: [
      { item: ITEMS.dragon_slayer, chance: 0.5 },
      { item: ITEMS.amulet_of_eternity, chance: 0.4 },
    ],
    skills: [
      { name: 'Inferno Breath', damage: 56, mpCost: 30, element: 'fire' },
      { name: 'Tail Slam', damage: 42, mpCost: 0 },
      { name: 'Magma Roar', damage: 65, mpCost: 40 },
    ],
    spriteColor: '#dc2626',
    avatarIcon: '🐉',
  },
};

export const NPCS: Record<string, NPC> = {
  elder_arin: {
    id: 'elder_arin',
    name: 'Elder Arin',
    title: 'Village Chieftain',
    zoneId: 'village',
    x: 8,
    y: 4,
    avatar: '👴',
    dialogue: [
      'Welcome, brave hero, to Oakhaven Village. Dark shadows stir in the Whispering Forest and Sunken Crypt.',
      'Malakor the Voidcaller seeks to unseal the primordial rift. Speak to Blacksmith Marcus and Guildmaster Vane to prepare for battle!',
      'May the ancient light guide your blade.',
    ],
    questId: 'quest_1',
  },
  blacksmith_marcus: {
    id: 'blacksmith_marcus',
    name: 'Marcus Anvilheart',
    title: 'Master Blacksmith',
    zoneId: 'village',
    x: 13,
    y: 6,
    avatar: '⚒️',
    dialogue: [
      'Need steel that never dulls? Marcus has forged weapons for heroes across three realms!',
      'Take a look at my wares or bring me materials from the Crypt.',
    ],
    shopItems: [
      ITEMS.rusty_sword,
      ITEMS.oak_staff,
      ITEMS.silver_dagger,
      ITEMS.iron_plate,
      ITEMS.wooden_buckler,
      ITEMS.iron_helm,
      ITEMS.leather_boots,
    ],
  },
  alchemist_lyra: {
    id: 'alchemist_lyra',
    name: 'Lyra Moonwhisper',
    title: 'Apothecary & Mystic',
    zoneId: 'village',
    x: 4,
    y: 7,
    avatar: '🧪',
    dialogue: [
      'The forest herbs hold ancient secrets. Never venture into danger without restorative potions!',
      'Drink deep of the vitality draughts when your flesh wearies.',
    ],
    shopItems: [
      ITEMS.hp_potion,
      ITEMS.large_hp_potion,
      ITEMS.mp_potion,
      ITEMS.fire_bomb,
      ITEMS.ruby_ring,
    ],
  },
  ranger_sylas: {
    id: 'ranger_sylas',
    name: 'Sylas Swiftwood',
    title: 'Pathfinder of the Wilds',
    zoneId: 'forest',
    x: 14,
    y: 4,
    avatar: '🏹',
    dialogue: [
      'Tread softly, wanderer. Wolves hunt in packs and goblin scouts ambush unwary travelers.',
      'To the deep north lies the entrance to the ancient Sunken Crypt. Only champions enter there.',
    ],
    questId: 'quest_2',
  },
};

export const INITIAL_QUESTS: Quest[] = [
  {
    id: 'quest_1',
    title: 'Cleansing the Woodland',
    giver: 'Elder Arin',
    zone: 'Whispering Forest',
    description: 'Wild beasts and goblin scavengers threaten the trade caravans outside Oakhaven.',
    objective: 'Defeat 3 beasts or goblins in Whispering Forest',
    currentCount: 0,
    targetCount: 3,
    rewardGold: 75,
    rewardXp: 120,
    rewardItem: ITEMS.silver_dagger,
    isCompleted: false,
    isClaimed: false,
  },
  {
    id: 'quest_2',
    title: 'Shadow in the Crypt',
    giver: 'Sylas Swiftwood',
    zone: 'Sunken Crypt',
    description: 'Venture into the subterranean ruins to vanquish Malakor the Voidcaller before his ritual concludes.',
    objective: 'Defeat Malakor in the Sunken Crypt',
    currentCount: 0,
    targetCount: 1,
    rewardGold: 250,
    rewardXp: 400,
    rewardItem: ITEMS.paladin_aegis,
    isCompleted: false,
    isClaimed: false,
  },
  {
    id: 'quest_3',
    title: "Wyrm of Molten Peak",
    giver: 'Elder Arin',
    zone: 'Dragon Crag',
    description: 'Ascend the volcanic heights and conquer Ignis Prime Dragon to secure peace forever.',
    objective: 'Defeat Ignis Prime on Molten Peak',
    currentCount: 0,
    targetCount: 1,
    rewardGold: 500,
    rewardXp: 800,
    rewardItem: ITEMS.amulet_of_eternity,
    isCompleted: false,
    isClaimed: false,
  },
];
